-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 11:46:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organisation` (
  `idOrganisation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT 'none',
  `adresse` VARCHAR(45) NOT NULL DEFAULT 'none',
  `idCivil` INT NOT NULL,
  `commentaire` VARCHAR(45) NOT NULL DEFAULT 'none',
  `founded` DATETIME NOT NULL,
  `modification` DATETIME NULL,
  `incidentDelcared` INT NOT NULL DEFAULT 0,
  `historiqueMissionImplique` VARCHAR(45) NOT NULL DEFAULT 0,
  `historique` INT NOT NULL DEFAULT none,
  PRIMARY KEY (`idOrganisation`),
  INDEX `dirigeant_idx` (`idCivil` ASC) VISIBLE,
  CONSTRAINT `fk_idCivil`
    FOREIGN KEY (`idCivil`)
    REFERENCES `mydb`.`Civil` (`idCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InscriptionOrganisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InscriptionOrganisation` (
  `idInscriptionOrganisation` INT NOT NULL AUTO_INCREMENT,
  `idOrganisation` INT NOT NULL,
  PRIMARY KEY (`idInscriptionOrganisation`),
  UNIQUE INDEX `inscription_UNIQUE` (`idOrganisation` ASC) VISIBLE,
  CONSTRAINT `fk_idOrganisation`
    FOREIGN KEY (`idOrganisation`)
    REFERENCES `mydb`.`Organisation` (`idOrganisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Civil` (
  `idCivil` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `birth` DATETIME NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `death` DATETIME NOT NULL DEFAULT alive,
  `idInscriptionOrganisation` INT NOT NULL DEFAULT none,
  PRIMARY KEY (`idCivil`),
  INDEX `fk_abonnement_idx` (`idInscriptionOrganisation` ASC) VISIBLE,
  CONSTRAINT `fk_idInscriptionOrganisation`
    FOREIGN KEY (`idInscriptionOrganisation`)
    REFERENCES `mydb`.`InscriptionOrganisation` (`idInscriptionOrganisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Incident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Incident` (
  `idIncident` INT NOT NULL AUTO_INCREMENT,
  `localisationDepartIncident` VARCHAR(45) NULL,
  `localisationFinIncident` VARCHAR(45) NULL,
  `heureDebutIncident` DATETIME NULL,
  `heureFinIncident` DATETIME NULL,
  `idCivil` INT NULL,
  `idSuperHero` INT NULL,
  `idSuperVilain` INT NULL,
  PRIMARY KEY (`idIncident`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoriqueIncident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HistoriqueIncident` (
  `idHistoriqueIncident` INT NOT NULL AUTO_INCREMENT,
  `idCivil` INT NULL,
  `idIncident` INT NULL,
  PRIMARY KEY (`idHistoriqueIncident`),
  INDEX `fk_organisationImplique_idx` (`idCivil` ASC) VISIBLE,
  INDEX `fk-idIncidentDeclare_idx` (`idIncident` ASC) VISIBLE,
  CONSTRAINT `fk_idCivilImplique`
    FOREIGN KEY (`idCivil`)
    REFERENCES `mydb`.`Civil` (`idCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-idIncidentDeclare`
    FOREIGN KEY (`idIncident`)
    REFERENCES `mydb`.`Incident` (`idIncident`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pouvoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pouvoir` (
  `idPouvoir` INT NOT NULL AUTO_INCREMENT,
  `eau` INT NOT NULL DEFAULT 0,
  `feu` INT NOT NULL DEFAULT 0,
  `eletricity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPouvoir`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Score` (
  `idScore` INT NOT NULL AUTO_INCREMENT,
  `score` INT NULL DEFAULT 50,
  PRIMARY KEY (`idScore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SuperHero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SuperHero` (
  `idSuperHero` INT NOT NULL AUTO_INCREMENT,
  `idCivil` INT NOT NULL DEFAULT none,
  `name` VARCHAR(45) NOT NULL DEFAULT 'none',
  `idPouvoir` INT NULL,
  `idScore` INT NULL,
  PRIMARY KEY (`idSuperHero`),
  INDEX `pk_identiteSecrete_idx` (`idCivil` ASC) VISIBLE,
  INDEX `pk_capacite_idx` (`idPouvoir` ASC) VISIBLE,
  INDEX `fk_note_idx` (`idScore` ASC) VISIBLE,
  CONSTRAINT `fk_idCivil`
    FOREIGN KEY (`idCivil`)
    REFERENCES `mydb`.`Civil` (`idCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPouvoir`
    FOREIGN KEY (`idPouvoir`)
    REFERENCES `mydb`.`Pouvoir` (`idPouvoir`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idScore`
    FOREIGN KEY (`idScore`)
    REFERENCES `mydb`.`Score` (`idScore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SuperVilain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SuperVilain` (
  `idSuperVilains` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idCivil` INT NULL,
  `idPouvoir` INT NULL,
  `nombreMefait` INT NULL,
  `coutDegat` INT NULL,
  `idIncident` INT NULL,
  PRIMARY KEY (`idSuperVilains`),
  INDEX `fk_identiteSecrete_idx` (`idCivil` ASC) VISIBLE,
  INDEX `fk_capacite_idx` (`idPouvoir` ASC) VISIBLE,
  INDEX `fk_victime_idx` (`idIncident` ASC) VISIBLE,
  CONSTRAINT `fk_identiteSecrete`
    FOREIGN KEY (`idCivil`)
    REFERENCES `mydb`.`Civil` (`idCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPouvoir`
    FOREIGN KEY (`idPouvoir`)
    REFERENCES `mydb`.`Pouvoir` (`idPouvoir`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCivil`
    FOREIGN KEY (`idIncident`)
    REFERENCES `mydb`.`Incident` (`idIncident`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mission` (
  `idMission` INT NOT NULL AUTO_INCREMENT,
  `idIncident` INT NULL,
  `statutMission` INT NULL,
  PRIMARY KEY (`idMission`),
  INDEX `fk_id_incident_idx` (`idIncident` ASC) VISIBLE,
  CONSTRAINT `fk_id_incident`
    FOREIGN KEY (`idIncident`)
    REFERENCES `mydb`.`Incident` (`idIncident`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `niveauDroit` INT NULL,
  `idCivil` INT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_idCivil_idx` (`idCivil` ASC) VISIBLE,
  CONSTRAINT `fk_idCivil`
    FOREIGN KEY (`idCivil`)
    REFERENCES `mydb`.`Civil` (`idCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
